### ISSUE TITLE
XFC0000	Cannot resolve type ":AdvancedEntry"

### ISSUE THREAD

**Issue by tekinomikata** [enisn/UraniumUI#135]
I could not find any information about this, I am using the example available at https://enisn-projects.io/docs/en/uranium/latest/themes/material/components/TextField

And when I try to compile or run I get the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	XFC0000	Cannot resolve type ":AdvancedEntry".	TestProject	F:\Projects\TestProject\TestProject\Features\Login\LoginView.xaml	28	
```
Which goes to
```xaml
<material:TextField Title="Email:" AllowClear="True"
                    Icon="{FontImageSource FontFamily=FASolid, Glyph={x:Static fa:Solid.Envelope}}">
    <validation:RequiredValidation />
    <validation:RegexValidation Pattern="{x:Static input:AdvancedEntry.REGEX_EMAIL}" Message="My Error Message!" />
</material:TextField>
```
Line 28 being:
```xaml
<validation:RegexValidation Pattern="{x:Static input:AdvancedEntry.REGEX_EMAIL}" Message="My Error Message!" />
```
And I have the following namespaces defined
```xaml
xmlns:material="clr-namespace:UraniumUI.Material.Controls;assembly=UraniumUI.Material"
xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"
xmlns:fa="clr-namespace:UraniumUI.Icons.FontAwesome;assembly=UraniumUI.Icons.FontAwesome"
```

What am I doing wrong here? I cannot find anything on it.

**Comment by enisn** [comment]
Hi @tekinomikata 

Sorry, it's my bad. There is a missing information on documentation. `REGEX_EMAIL` comes from a different namespace. 

Can you please try adding the following namespace to your page:
https://github.com/enisn/UraniumUI/blob/1c8e59451b561f0e15e5de0baaafb06b83438374/demo/UraniumApp/Pages/InputFieldsPage.xaml#L5

Or you can remove Email validation rule since it's not inluded UraniumUI. That validation comes from InputKit.

**Comment by tekinomikata** [comment]
> ```
> xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"
> ```

Awesome that in addition to adding the nuget for InputKit did the trick.

Thanks a lot.
