### ISSUE TITLE
DataGrid - missing horizontal seperator

### ISSUE THREAD

**Issue by enisn** [enisn/UraniumUI#190]
The horizontal seperator is missing after first row.

---

        > > **Here is the scroll bar :** ![image](https://user-images.githubusercontent.com/41630728/211163382-d89ce4b8-57aa-4423-ba49-8edf9ee84636.png)
> > I can see a missing horizontal divider after the first row. That issue was fixed, you can update to the latest version.

I am on the latest version actually, but I can still report this issue. (I don't mind much personally. Everything else is great)
![image](https://user-images.githubusercontent.com/41630728/211164007-2c4d0ded-b293-4fe2-9241-433bfdbf2b4e.png)

_Originally posted by @YBTopaz8 in https://github.com/enisn/UraniumUI/issues/63#issuecomment-1374551488_

**Comment by enisn** [comment]
I couldn't reproduce the issue with the latest version (v2.2.0)

Removing `bin` and `obj` folders after upgrading might help

**Comment by YBTopaz8** [comment]
> I couldn't reproduce the issue with the latest version (v2.2.0)
> 
> Removing `bin` and `obj` folders after upgrading might help

I removed `bin` and `obj` folders, cleaned the solution, used `dotnet restore`, rebuilt the solution then launched, but still, no horizontal separator.
Just reporting in

**Comment by enisn** [comment]
Thanks for the information, I couldn't reproduce the issue. Can you give more information about your datagrid usage?

Are you using auto columns or custom columns etc?

**Comment by YBTopaz8** [comment]
You're welcome!
So, in full;
- No, I do not use Auto Columns
- I implemented my own TitleView in which I add a HLayout that contains the Title as Label and 2 images (they are arrows that indicate whether the data is sorted Up or Down). The HLayouts have TapGesture Recognizers, used to do the sorting
- I also have CellItemTemplates that I use to stylize the appearance of my data.

**Here is a full view of my implementation for now.**

![image](https://user-images.githubusercontent.com/41630728/211172810-23e775ba-5238-417a-84ba-a93b312b0fcf.png)

Here is a quick video of the sorting I implemented (for some reason, my mouse doesn't show, but the arrow is an indication)

https://user-images.githubusercontent.com/41630728/211172893-53c22fff-54bc-40f8-911d-5471513bdcb5.mp4

**Comment by YBTopaz8** [comment]
Something quite strange is happening now.
For some reason, the Line seems to be appearing;
Some context: ( it's a bit long, but I wish to explain my process, maybe details can help)
I use an ObservableCollection from my VM as ItemsSource for DataGrid and as you can see in the previous video, the horizontal separator will never appear whether it's for the first or the nth time (during sorting/filtering).
Anyway, since it never bothered me much, I shifted my focus to something else, I was busy implementing sorting my data on the DG. (meaning I need to rearrange my data in ascending/descending order),
Since I'm working on .Net MAUI for Android and Windows both share the same VM and its logic.
On Android, whenever I tap to sort, all the data is very quickly rearranged (<1s) but on Windows it takes 2 to 6 seconds. 
Which is very annoying to me as I can't even understand why it is that slow.
I did some research and one of the possibilities for the slowness could have been that `ObservableCollections` raison an `OnPropertyChanged` and `OnCollectionChanged` event whenever I `add()`, `remove()` items or `clear()`  the collection.
So in a case of 100 items, it _Could_ have been the cause of the slowness.
Anyway on StackOverFlow, I found [this solution](https://stackoverflow.com/a/13303245/9790630) , which was basically me creating a SubClass of `ObservableCollection` and calling the property changes events only after adding all the data.
ANYWAY, I noticed that when using my SubClass as ItemsSource for the DG, the Horizontal Separator is CONSTANTLY present 😄  

I suppose it is not a straightforward solution to YOUR issue, but I hope it gives an insight.

I still have that slowness when sorting though. :( 

Here is a video showing my files and showing that the line does indeed appear.

https://user-images.githubusercontent.com/41630728/211174268-deaa3673-5ef3-477f-a428-901f7fa4494f.mp4

**Comment by YBTopaz8** [comment]
One Last thing, 
I initially suspected that maybe the DataGrid was the source of the slowness on windows platform (since I don't used DG on Android). 
I can confirm that it is NOT the issue. Your Data Grid, so far is Great! 
I tested using the `CollectionView` and DataGrid on Windows Platform simultaneously and they both update at the same time (2-3s long).
Just clearing some doubts if any.
I'm happy that my sorting implementation works, but I'm mad because it's _Slow_
I'll keep looking into it though

**Comment by enisn** [comment]
Thank you for your explanation and research. I think I understood the issue and will work on it. 


> One Last thing, I initially suspected that maybe the DataGrid was the source of the slowness on windows platform (since I don't used DG on Android). I can confirm that it is NOT the issue. Your Data Grid, so far is Great! I tested using the `CollectionView` and DataGrid on Windows Platform simultaneously and they both update at the same time (2-3s long). Just clearing some doubts if any. I'm happy that my sorting implementation works, but I'm made because it's _Slow_ I'll keep looking into it though

This might be the reason for the slowness since there is no `Reset` implementation and renders the entire datagrid again when the collection is reset.
https://github.com/enisn/UraniumUI/blob/2ce9e5a7a2354673e777cb1ad3dc1d8b97e0fdda/src/UraniumUI.Material/Controls/DataGrid.cs#L100-L101

**Comment by YBTopaz8** [comment]
Thanks for your reply!
Given that the `DataGrid` AND the `CollectionView` were both equally slow ON WINDOWS, I couldn't suspect and blame your `DataGrid` and I thought it was as platform issue.

I'll check into the `CollectionView` 's implementation to see if it has a `Reset` action.

I can see that you've implemented `add()` and `remove()` but no reset indeed.
I'll try and edit my SubClass to remove and notify THEN add and notify. 
Sounds like a long road but I'll see if it makes any changes speed wise.

I'll report unfailingly.

**Comment by enisn** [comment]
Solved by #192 
Thank you for your effort

**Comment by YBTopaz8** [comment]
Sorry for reopening this. I just wanted to come back with my findings after numerous tests on how to implement sorting;

- I tried switching `Reset` to `Add` and `Remove` or even `Replace` but I always got an exception message saying "the constructor accepts Reset as parameter (Action). The Exception occurred here :
![image](https://user-images.githubusercontent.com/41630728/211198395-cc173d48-ae69-48bd-8abb-4c820f0c2ea0.png)

- I reverted to using `Reset` but with `CollectionView` ONLY this time, and I still noticed that the sorting process was equally as slow. The process is as follows `Sort_Btn_Clicked` -> `List.Clear() is done` -> `list.AddRange() will add items using Foreach` -> `OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));` will be done. Interestingly, the slowness arises ONLY when `OnCollectionChanged` is being executed. It can take between 3 to 6s to finish in total sometimes more.
- All of this slowness is observed ONLY on Windows platform. Android is very very fast (<1ms)
- I would like to raise an issue on the MAUI repo but I won't even know how to explain it honestly. So, maybe I will remove sorting on windows while waiting for an Update.

While waiting for your next update, Thank you for your work ❤️
