### ISSUE TITLE
Ability to disable/remove TabView ScrollView

### ISSUE THREAD

**Issue by daltzctr** [enisn/UraniumUI#328]
I affectively want to create a TabViewHeaderItem whose width is the same as all other items, and non-scrollable. Unfortunately, I don't see an easy way to do this.

![image](https://github.com/enisn/UraniumUI/assets/105223895/f2fa87d9-745f-4dc7-a138-6b23731a3ac1)

**Comment by daltzctr** [comment]
I've accomplished this by setting the `TabViewHeaderItem.ItemTemplate` content (of type `Frame`) `HorizontalOptions` to `FillAndExpand` and removed and underlying width properties.

**Comment by daltzctr** [comment]
Hm, this actually seems to be broken on android with the last tab being cut off for some reason

**Comment by enisn** [comment]
TabView has `ItemsSource` and tab count is dynamic, so scroll should be exist in tabs, but I understand your situation, you want to fill to exact screen width but it's not possible with current situation of tabview.

I'll consider it I'll put an option to enable/disable it. Since it might be a breaking change, it'll be done in v2.5

**Comment by enisn** [comment]
Since `TabHeaderItemColumnWidth` added, this is no longer an issue
