### ISSUE TITLE
BUG with DisplayViewAsync in the UraniumUI Community Toolkit.

### ISSUE THREAD

**Issue by GuyFlorent** [enisn/UraniumUI#697]
I am encountering an issue with the ![Screenshot_2024-07-03-14-42-02-386-edit_com companyname ordersent](https://github.com/enisn/UraniumUI/assets/55955603/059f5bfd-104f-4b4f-96aa-cb8ff8a3002c) The "OK" button does not appear, which blocks the application and prevents any further interaction.

Could you please assist me in resolving this issue so that the "OK" button displays correctly and the application functions without blocking?

Thank you in advance for your help.

please see the image joinned
![Screenshot_2024-07-03-14-42-02-386-edit_com companyname ordersent](https://github.com/enisn/UraniumUI/assets/55955603/3b927999-424c-4ddc-9827-075ab132db1c)

Best regards,

**Comment by GuyFlorent** [comment]
There is no problem with Mopups it's only in community toolkit uranium

**Comment by enisn** [comment]
Hello, `DisplayViewAsync` is developed for internal usage but since it's public you can use it but it'll be removed in the future because of viewmodel-view coupling. It gets `View` as a parameter and it makes it dependent on MAUI layer. `IDialogService` will be moved into netstandard library and it'll not have any reference to the MAUI Sdk.

I won't completely drop this displaying view functionality, I can move it to an external method as it is currently.

---

Still, I'll investigate this problem in a short term 👍

**Comment by GuyFlorent** [comment]
Thank you for your answer, still waiting

**Comment by enisn** [comment]
Solved with enhancement in PR https://github.com/enisn/UraniumUI/pull/706

```csharp
private async void Button_Clicked(object sender, EventArgs e)
{
    await UraniumServiceProvider.Current.GetService<CommunityToolkitDialogService>()
        .DisplayViewAsync("Hello", new Label { Text = "Hello World!" }, "OK");
}
```

![image](https://github.com/enisn/UraniumUI/assets/23705418/b4d1d8da-ad36-40b5-b1f4-d1d77c9d2d02)
