### ISSUE TITLE
Memory Leaks Report

### ISSUE THREAD

**Issue by usefulBeeing** [enisn/UraniumUI#727]
I tested UraniumUI for possible leaks using a [wrapper ](https://github.com/usefulBeeing/SimplifiedLeakDetector.Maui) around [MemoryToolkit](https://github.com/AdamEssenmacher/MemoryToolkit.Maui). The result came as seen in the screenshot when tested against `<material:AutoCompleteTextField />`. I also came across other UI packages that did not leak, so if they can avoid those leaks, I'm sure UraniumUI could too!

<img width="517" alt="_materialUI" src="https://github.com/user-attachments/assets/9f3227ee-e31c-4cc3-b35b-cfdd47b1be02">

**Comment by enisn** [comment]
Hi, thanks for the report 🎉🙏

Can you provide which platform you run tests on? AutoCompleteView has different implementations on each platform, so I can find where to start checking, thanks

**Comment by usefulBeeing** [comment]
Thank you @enisn for your quick response :rocket:. The [SimplifiedLeakDetector](https://github.com/usefulBeeing/SimplifiedLeakDetector.Maui) wrapper I tested with is a [.NET MAUI](https://github.com/dotnet/maui) project. I added the two NuGet packages through Visual Studio Version 17.10.4.


<img width="352" alt="_material3" src="https://github.com/user-attachments/assets/741773fd-56d3-4780-8fcd-54b6a8704601">


<img width="337" alt="_material4" src="https://github.com/user-attachments/assets/e5376977-07dd-471d-859e-a63890a9d158">

**Comment by enisn** [comment]
I found the leak source.

The MemoryToolkit library warns because of the following Geometry instances. UraniumUI components always use the same instance of Geometry classes for optimization. Since they're a static field of a class, they won't be disposed. The tool you measure finds it and throws warning.
https://github.com/enisn/UraniumUI/blob/92202bd81ff6bd32c177d2e9296c07619e1e7827/src/UraniumUI/Pages/UraniumShapes.cs#L7-L13

When I replace `=` operator with `=>` all the warnings are gone. But this is not what I want. In this scenario each control will have different Geometry instance and they'll consume **n** times more memory according to number of components in the page
<img src="https://github.com/user-attachments/assets/3a48b973-8643-4e0d-ab28-83078cd02515" height="240" />

Still I'll take a look a deep memory analyze if it's better to use different instances or not
