### ISSUE TITLE
TimePickerField (TapGestureRecognizer.add_Tapped) Method not found 

### ISSUE THREAD

**Issue by gpproton** [enisn/UraniumUI#74]
I kept getting using TimePickerField control, i'm not sure what the issue is
but any advice will be appreciated.

System.MissingMethodException
Message=Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler)

Version: UraniumUI.Material 0.13.1

```csharp
new FormView {
      Spacing = 20,
      Children = {
          new TimePickerField {
          Title = "Sample Picker",
          Icon = new FontImageSource() { FontFamily = "FASolid", Glyph = FA.Solid.Clock }
          }
      }
  }
```

**Comment by enisn** [comment]
Which MAUI version do you use?


---
`.Net 7.0` isn't supported yet since it's not fully released.

This project is based on `6.0.536`
https://github.com/enisn/UraniumUI/blob/develop/maui.common.props#L3

if you're already installed `.NET 7.0-rc.2` SDK or you're not sure which .Net version are you using, you can pin your project version via adding following section in your **.csproj** file.

```xml
<MauiVersion>6.0.536</MauiVersion>
```

**Comment by gpproton** [comment]
Thanks, after i reverted to .net 6.0 the error stopped.
