### ISSUE TITLE
DataGrid - Show Error When Empty

### ISSUE THREAD

**Issue by supershopping** [enisn/UraniumUI#99]
In my project , I am trying to using "Items.Clear()" on a DataGrid binding. 
I run the demo app from UraniumUI, in SelectableDataGridPage, when removed all the item from Items, I am getting error message "System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'

Edit:

This also work.

    foreach (var item in SelectedItems.ToList())
    {
        Items.Remove(item);
    }

**Comment by enisn** [comment]
Clearing all the items one by one until no items remain occurs problem on the enumerator. `ObservableCollection` sends changes one by one. You can prevent enumerator usage by using `for` instead of `foreach` in your ViewModel, or just call `Clear()` command instead. After clear method usage, ObservableCollection sends all the deletion operations at once, so Datagrid will know all of them are removed and it can clear all the content at once instead of removing rows one by one.

When equals SelectedItems and Items.
```csharp
    // It's not ok ❌
    foreach (var item in SelectedItems)
    {
        Items.Remove(item);
    }
    
    // the following is OK ✅
    for (int i = 0; i < SelectedItems.Count; i++)
    {
        Items.Remove(SelectedItems[i]);
    }

    // also the following is OK too✅
    Items.Clear();
```

Most probably DataGrid sends the last state of the Items over binding after the last item is removed.
